### ISSUE TITLE
Unable to generate command results

### ISSUE THREAD

**Issue by chensivan** [TellinaTool/tellina#3]
I successfully setup Tellina on my Mac (10.12.5) and ran it on Tensorflow (>1). But I am not able to get any results. I am relatively new to Tensorflow, maybe I am wrong on some trivial steps, any help is appreciated!

![image](https://user-images.githubusercontent.com/2650733/28031068-1fb50c7a-6574-11e7-928b-b68c67c242b1.png)

![image](https://user-images.githubusercontent.com/2650733/28031077-286eb0d2-6574-11e7-9a3a-6c2562b5cdfb.png)

**Comment by todpole3** [comment]
Have you tried setting WEBSITE_DEVELOP in website/view.py to False? When it is setting to True the Tensorflow part is not called.

Sorry that wasn't clear in the documentation.

**Comment by chensivan** [comment]
Aha, yes, it works now. Thank you for the help!
