### ISSUE TITLE
Tellina.rocks doesn't seem to be working

### ISSUE THREAD

**Issue by tomlagier** [TellinaTool/tellina#9]
Entering a command just refreshes the results pane with the suggested results, rather than actually displaying results to the query. Additionally, the following error is in the console:

```
jquery-3.1.1.js:9615 GET http://ipinfo.io/?callback=jQuery3110597133837088712_1593799460508&_=1593799460509 net::ERR_ABORTED 429 (Too Many Requests)
send @ jquery-3.1.1.js:9615
ajax @ jquery-3.1.1.js:9143
jQuery.<computed> @ jquery-3.1.1.js:9292
(anonymous) @ translate?request_str=find all files in the "foo/" directory&ip_address=:189
```

**Comment by todpole3** [comment]
I tried the following URL and refreshing is working for me:
http://kirin.cs.washington.edu:8000/translate?request_str=find%20all%20files%20in%20the%20%22foo/%22%20directory&ip_address=67.169.95.117

Are you still experiencing this issue? Do you experience them for all queries or some of the queries? Could you post some URLs that will trigger the problem? Thanks.

**Comment by tomlagier** [comment]
Just tried again, and it looks like the tool is working correctly - this is the output I see:

<img width="1052" alt="Screen Shot 2020-07-05 at 4 34 53 PM" src="https://user-images.githubusercontent.com/3165151/86544652-806e8d00-bedd-11ea-8e00-95057a1576ec.png">

**Comment by todpole3** [comment]
I think it's right. Previously you might hit the problem because too many users are using it at the same time.

**Comment by tomlagier** [comment]
Ah great, thanks. Closing.
